### ISSUE TITLE
[Enhancement] Add --json option, function which output JSON-formatted data

### ISSUE THREAD

**Issue by michaelborn** [bmc0/musicbrainz_discid#1]
I am using this program for my capstone, and will be storing the data in a mongo database. However, there is currently no way to parse this data into a program-friendly format.

Would you accept a pull request which added a "--json" option and function? I'm open to ideas. Otherwise I may fork and start a new project, or re-write this in Node.JS.

**Comment by bmc0** [comment]
Could be useful, so sure. Forking may be easier in the long run if you want to change very much though.

The MusicBrainz web service does support direct JSON output instead of the normal XML (See http://wiki.musicbrainz.org/Development/JSON_Web_Service). The only problem is that it's not considered stable yet.
